# This workflow is used whenever we merge to integration.
# When the merge happens, this workflow will run. So don't add anything here that you wouldn't
# want to run all the time.
# DO NOT RUN TESTS AGAINST THE INT ENVIRONMENT FROM HERE
# Jobs can be run sequentially or in parallel
name: integration main workflow

on:
  push:
    branches:
       - main

jobs:
  tag-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
          tag_prefix: 'example-'
      - name: Build the packages
        run: tox -e build
